// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-courts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courts_default = defineTool({
  name: "list_courts",
  title: "Listar canchas",
  description: "Lista canchas activas en PlayOn. Filtra opcionalmente por deporte y/o municipio de Monterrey.",
  inputSchema: {
    sport: z.string().optional().describe("Deporte (ej. futbol, tenis, padel)"),
    municipio: z.string().optional().describe("Municipio de la Zona Metropolitana de Monterrey"),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (por defecto 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sport, municipio, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("courts").select("id, name, sport, municipio, address, price_per_hour, image_url, description").eq("is_active", true).limit(limit ?? 20);
    if (sport) query = query.eq("sport", sport);
    if (municipio) query = query.ilike("municipio", `%${municipio}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-matches.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_matches_default = defineTool2({
  name: "list_open_matches",
  title: "Listar partidos abiertos",
  description: "Lista los pr\xF3ximos partidos abiertos en PlayOn con cupos disponibles.",
  inputSchema: {
    sport: z2.string().optional().describe("Filtra por deporte"),
    skill_level: z2.string().optional().describe("Nivel: beginner, intermediate, advanced"),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sport, skill_level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("matches").select("id, sport, title, location, starts_at, duration_minutes, max_players, skill_level, price_per_player, status, notes").gte("starts_at", (/* @__PURE__ */ new Date()).toISOString()).in("status", ["open", "scheduled"]).order("starts_at", { ascending: true }).limit(limit ?? 20);
    if (sport) query = query.eq("sport", sport);
    if (skill_level) query = query.eq("skill_level", skill_level);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Ver mi perfil",
  description: "Devuelve el perfil PlayOn del usuario autenticado (deportes, nivel, municipio, disponibilidad).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("profiles").select("id, display_name, bio, municipio, colonia, sports, skill_level, availability, rating, avatar_url, onboarded").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-matches.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_matches_default = defineTool4({
  name: "list_my_matches",
  title: "Mis partidos",
  description: "Lista los partidos en los que el usuario autenticado participa o es organizador.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const uid = ctx.getUserId();
    const { data: participating, error: e1 } = await supabase.from("match_participants").select("status, joined_at, match:matches(id, sport, title, starts_at, location, status, max_players, price_per_player)").eq("user_id", uid);
    if (e1) return { content: [{ type: "text", text: e1.message }], isError: true };
    const { data: hosting, error: e2 } = await supabase.from("matches").select("id, sport, title, starts_at, location, status, max_players, price_per_player").eq("host_id", uid);
    if (e2) return { content: [{ type: "text", text: e2.message }], isError: true };
    const payload = { hosting: hosting ?? [], participating: participating ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/join-match.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var join_match_default = defineTool5({
  name: "join_match",
  title: "Unirse a un partido",
  description: "Registra al usuario autenticado como participante de un partido de PlayOn por su id.",
  inputSchema: {
    match_id: z3.string().uuid().describe("UUID del partido al que unirse")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("match_participants").insert({ match_id, user_id: ctx.getUserId(), status: "confirmed" }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Te uniste al partido ${match_id}` }],
      structuredContent: { participant: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tkziycwbbpjvnlfnzwbt";
var mcp_default = defineMcp({
  name: "playon-mcp",
  title: "PlayOn MCP",
  version: "0.1.0",
  instructions: "Herramientas para PlayOn, la comunidad deportiva de Monterrey. Usa `list_courts` para descubrir canchas, `list_open_matches` para ver partidos abiertos, `get_my_profile` y `list_my_matches` para el perfil y partidos del usuario, y `join_match` para unirse a un partido por id.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courts_default, list_open_matches_default, get_my_profile_default, list_my_matches_default, join_match_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
