// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// En iOS/Android el localStorage del WKWebView puede ser purgado por el sistema;
// Preferences usa storage nativo (UserDefaults/SharedPreferences) que persiste.
// Migra una sola vez la sesión existente de localStorage para no desloguear a nadie.
const nativeStorage = {
  getItem: async (key: string) => {
    const { value } = await Preferences.get({ key });
    if (value !== null) return value;
    const legacy = localStorage.getItem(key);
    if (legacy !== null) {
      await Preferences.set({ key, value: legacy });
      localStorage.removeItem(key);
    }
    return legacy;
  },
  setItem: async (key: string, value: string) => {
    await Preferences.set({ key, value });
  },
  removeItem: async (key: string) => {
    await Preferences.remove({ key });
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: Capacitor.isNativePlatform() ? nativeStorage : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
